# Generated by Django 6.0.4 on 2026-04-21 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_article_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='articles',
            field=models.ManyToManyField(blank=True, to='news_app.article'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('editor', 'Editor'), ('journalist', 'Journalist')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_journalists',
            field=models.ManyToManyField(blank=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='subscribed_publishers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='news_app.publisher'),
        ),
    ]
